---
format: 
  revealjs:
    transition-speed: fast
    slide-number: c/t
    css: slides.css
    transition: fade
    incremental: false 
    theme: default
    footer: "Slides URL: <https://ibsar-cv-workshop.patrickli.org/> | Canberra time <span id = 'mel-local-time'></span>"
    logo: slide_figures/ANU_Primary_Horizontal_GoldBlack.png
    self-contained: true
    include-in-header: 
      - file: slides.js
    filters:
      - slides.lua
date: "`r Sys.Date()`"
---

## Deep Learning and Computer Vision in R: A Practical Introduction {.title-slide-title}

::: {.title-slide-event}

BIBC2025 workshop

:::

#### Patrick Li {.title-slide-author}

::: {.title-slide-org}

RSFAS, ANU

:::

---

## About me

I am Patrick Li

- Education background
- Current work
- Past experience in CV

---

## Content summary

- **Overview of computer vision (CV)**
- `reticulate` basics
- Neural networks
- Image classification
- Hyperparameter tuning
- CV model interpretation
- Object detection
- Image segmentation

---

## Disclaimer

::: {.callout-note}

## Code and theory

This workshop is a hands-on introduction to modern computer vision in R.
You’ll work through code examples and practical exercises.
Theory will be covered only to the extent needed to understand the key ideas and statistical foundations behind the models.

:::

::: {.callout-warning}

## Reproducibility

Computer vision models can be only partly reproducible due to GPU computation.
Don’t be surprised if your results differ from those shown in the materials.

:::

---

## Expectation

<br>

**How confident should I be coming into this workshop?**

. . .

<br>

::: {.text-90}

If you have a statistics background, you are good to go! 

There will be some new concepts and terminology, but nearly everything can be explained in statistical terms. Don’t be intimidated by CV jargon.

:::

---

## Overview of computer vision {.transition-slide}

---

## Computer vision


::: {.callout-note appearance="minimal"}

## Computer vision is a broad field concerned with enabling machines to interpret and understand visual information from the world. 

:::

::: {.text-70}


- **Image classification**: Assign a single label to an entire image.
- **Object detection**: Locate and classify multiple objects within an image using bounding boxes.
- **Image segmentation**: Label each pixel with a class, producing a detailed mask of objects.
- Image generation: Create realistic or artistic images from scratch or from a condition.
- Action recognition: Identify actions or activities in images or video sequences.
- Visual Question Answering: Answer questions about an image by understanding its content.
- ...

:::